// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAffix: typeof import('ant-design-vue/es')['Affix']
    ABackTop: typeof import('ant-design-vue/es')['BackTop']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    ACollapse: typeof import('ant-design-vue/es')['Collapse']
    ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel']
    ADescriptions: typeof import('ant-design-vue/es')['Descriptions']
    ADescriptionsItem: typeof import('ant-design-vue/es')['DescriptionsItem']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AImage: typeof import('ant-design-vue/es')['Image']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    ARow: typeof import('ant-design-vue/es')['Row']
    ClipBoard: typeof import('./src/components/ClipBoard/ClipBoard.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor/CodeEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/SvgIcon.vue')['default']
  }
}
